language: node_js
dist: bionic
sudo: required
git:
  depth: false
 
node_js:
 - 7
 
before_install:
 # Key for cran trusty ppa
 - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 51716619E084DAB9

 # Dependencies
 - sudo apt-get install libv8-3.14-dev r-base r-base-dev libudunits2-dev libgdal-dev libgeos-dev libproj-dev fish -y
 - chmod +x travis-main.sh
 - sudo apt-get update

warnings_are_errors: false

script: ./travis-main.sh

notifications:
  email: false

