name: "Release"
on:
  workflow_dispatch:
  schedule:
    - cron: "15 11 * * 4"

jobs:
  release:
    if: github.repository_owner == 'covid19-forecast-hub-europe'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - run: |
          echo "TODAY=$(date +%Y.%m.%d)" >> $GITHUB_ENV

      - run: |
          gh release create v${{ env.TODAY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create issue about failure
        if: failure() && github.event_name != 'workflow_dispatch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue reopen 2632
