  
name: "UCLA"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * 3"
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

    - name: Install requirenments
      run: |
        pip3 install -r github-actions/LANL_Geneva_req.txt
        
    - name: Setup R
      run: |
         sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
         sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/'
         sudo apt update
         sudo apt install r-base
        
    - name: Setup Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action - Weekly Forecasts"  
      
    - name: Process UCLA
      env:
        AUTH: ${{ secrets.GITHUBTOKEN }}
      run: |
        # Execute Scripts
        git checkout UCLA_actions
        
        python3 code/auto_download/auto-download-ucla.py
        cd ./data-raw/UCLA-SuEIR
        Rscript UCLA-processing-script.R
        cd ../../
        
        # Push to Github
        git remote rm origin
        git remote add origin https://${AUTH}@github.com/KITmetricslab/covid19-forecast-hub-de.git > /dev/null 2>&1
        git add --all
        git commit -m "Weekly UCLA forecasts"
        git push --quiet --set-upstream origin HEAD:UCLA_actions
        echo "pushed to github"
        
        #create PR
        cd ./code/auto_download
        python3 create_PR.py "Weekly UCLA forecasts" "UCLA_actions"
        cd ../../
