name: Validations v2

on:
  # Instead of pull_request to be able to post comments
  pull_request_target:
    branches: [ main ]
    paths:
      - 'data-processed/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'epiforecasts/covid19-forecast-hub-europe-validations'

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip3 install -r stable-req.txt

    - name: Run Validations
      env:
        # Necessary for posting comments
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python3 main.py

