name: "Visualization/Validation/Evaluation"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *"
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    
    - name: Setup R
      run: |
         sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
         sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/'
         sudo apt update
         sudo apt install r-base

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

    - name: Install requirenments
      run: |
        pip3 install -r github-actions/pr_requirements.txt

    - name: Visualization
      run: |
        cd ./app_forecasts_de/code
        python3 ./data_preparation.py
        python3 ./prepare_truth_data.py
        python3 ./add_last_observed.py
        cd ../../code/visualization
        Rscript ./plot_current_forecasts.R	
        cd ../../
        
    - name: Validation
      run: |
        cd ./code/validation
        python3 ./get_commit_dates.py
        #python3 ./validate_truth.py
        cd ../../

    - name: Evaluation
      run: |
        cd ./evaluation
        Rscript ./evaluate_forecasts.R
        cd ../

    - name: Commit files
      env:
        AUTH: ${{ secrets.GITHUBTOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action - Vis/Val/Eval Update"
        git remote rm origin
        git remote add origin https://${AUTH}@github.com/KITmetricslab/covid19-forecast-hub-de.git > /dev/null 2>&1
        git pull origin master
        git add --all
        git commit -m "Daily Vis/Val/Eval update"
        
    - name: Push changes
      run: |
        git push --quiet --set-upstream origin HEAD:master
        echo "pushed to github"
